runtime: nodejs18
env: standard
instance_class: F1

handlers:
  - url: .*
    script: auto

automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: automatic
  max_concurrent_requests: 700
  max_instances: 3

service_account: granqvist-dev@gothic-venture-373811.iam.gserviceaccount.com
