steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/gothic-venture-373811/granqvist-dev-docker-container',
        '--build-arg',
        'NODE_ENV=$_NODE_ENV',
        '--build-arg',
        'GITHUB_ACCESS_TOKEN=$_GITHUB_ACCESS_TOKEN',
        '.',
      ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['push', 'gcr.io/gothic-venture-373811/granqvist-dev-docker-container']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'granqvist-dev',
        '--image',
        'gcr.io/gothic-venture-373811/granqvist-dev-docker-container',
        '--region',
        'europe-west1',
        '--allow-unauthenticated',
        '--max-instances',
        '30',
        '--min-instances',
        '0',
        '--memory',
        '128Mib',
        '--concurrency',
        '80',
      ]
images:
  - gcr.io/gothic-venture-373811/granqvist-dev-docker-container
