options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1600s'

steps:
  - name: node:18.12.1
    entrypoint: npm
    args: ['install']

  - name: node:18.12.1
    entrypoint: npm
    args: ['run', 'build']

  - name: node:18.12.1
    entrypoint: npm
    args: ['run', 'create-env']
    env:
      - 'GITHUB_ACCESS_TOKEN=$_GITHUB_ACCESS_TOKEN'
      - 'ENVIRONMENT=$_ENVIRONMENT'

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']

  - name: bash
    script:
      #!/usr/bin/env bash
      env
