steps:
  - name: Install dependencies
    entrypoint: npm
    args: ['install']
  - name: Create .env file in root dir
    entrypoint: npm
    args: ['run', 'create-env']
    env:
      - 'GITHUB_ACCESS_TOKEN=${_GITHUB_ACCESS_TOKEN}'
      - 'ENVIRONMENT=${_ENVIRONMENT}'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
options:
  logging: CLOUD_LOGGING_ONLY
timeout: '1600s'
